#spring.application.name=KAYA
#
#server.port=${PORT:8080}
#server.address=0.0.0.0
#server.servlet.context-path=/api
#
## DataSource — set PGHOST, PGPORT, PGDATABASE, PGUSER, PGPASSWORD env vars
#spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
#spring.datasource.username=${PGUSER}
#spring.datasource.password=${PGPASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.open-in-view=false
#spring.jpa.show-sql=false
#
## Allow long GA runs
#spring.mvc.async.request-timeout=600000

# ----------------------------------------------------------------------------------

spring.application.name=KAYA

spring.datasource.url=jdbc:postgresql://localhost:5432/kaya_db
spring.datasource.username=postgres
spring.datasource.password=123456

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true