package com.kaya.dataManager.excelHandler.exportHandler;

import com.kaya.model.Course;
import com.kaya.model.Lecture;
import com.kaya.model.TimeTable;
import lombok.RequiredArgsConstructor;
import org.dhatim.fastexcel.Color;
import org.dhatim.fastexcel.Workbook;
import org.dhatim.fastexcel.Worksheet;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.util.Comparator;
import java.util.List;

@Component
@RequiredArgsConstructor
public class ExportBuilder {

    private final DayPatternHelper dayPatternHelper;

    public ResponseEntity<byte[]> buildCoursesExport(List<Course> courses) throws Exception {

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try (Workbook wb = new Workbook(out, "KAYA Scheduler", "1.0")) {
            Worksheet ws = wb.newWorksheet("Courses");

            String[] headers = {"#", "Course Symbol", "Course Number", "Room Type", "Teaching Method"};
            for (int c = 0; c < headers.length; c++) {
                ws.value(0, c, headers[c]);
                ws.style(0, c).bold().set();
            }

            for (int r = 0; r < courses.size(); r++) {
                Course co = courses.get(r);
                ws.value(r + 1, 0, r + 1);
                ws.value(r + 1, 1, co.getCourseSymbol() != null ? co.getCourseSymbol() : "");
                ws.value(r + 1, 2, co.getCourseNumber() != null ? co.getCourseNumber() : "");
                ws.value(r + 1, 3, co.getRequiredRoomType() != null ? co.getRequiredRoomType().name() : "");
                ws.value(r + 1, 4, co.getTeachingMethod() != null ? co.getTeachingMethod().name() : "");
            }
        }

        return xlsxResponse(out, "courses.xlsx");
    }

    public ResponseEntity<byte[]> buildTimetableExport(TimeTable tt) throws Exception {
        // 1. Sort lectures: Course Symbol → Course Number → Section Number
        List<Lecture> scheduled = tt.getLectures().stream()
                .filter(l -> l.getTimeSlot() != null && l.getCourse() != null)
                .sorted(Comparator
                        .comparing((Lecture l) -> l.getCourse().getCourseSymbol() != null ? l.getCourse().getCourseSymbol() : "")
                        .thenComparing(l -> l.getCourse().getCourseNumber() != null ? l.getCourse().getCourseNumber() : "")
                        .thenComparingInt(l -> l.getSectionNumber() != null ? l.getSectionNumber() : 0))
                .toList();

        List<Lecture> unscheduled = tt.getLectures().stream()
                .filter(l -> l.getTimeSlot() == null && l.getCourse() != null)
                .sorted(Comparator
                        .comparing((Lecture l) -> l.getCourse().getCourseSymbol() != null ? l.getCourse().getCourseSymbol() : "")
                        .thenComparing(l -> l.getCourse().getCourseNumber() != null ? l.getCourse().getCourseNumber() : ""))
                .toList();

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try (Workbook wb = new Workbook(out, "KAYA Scheduler", "1.0")) {
            Worksheet ws = wb.newWorksheet("Timetable");

            // ── Row 0: Title ───────────────────────────────────────────────
            ws.value(0, 0, "KAYA \u2013 University Course Timetable System (Yarmouk University)");
            ws.style(0, 0)
                    .bold()
                    .fontSize(14)
                    .fontColor(Color.WHITE)
                    .fillColor("1F3864")
                    .set();

            // ── Row 1: Subtitle ────────────────────────────────────────────
            ws.value(1, 0, "Generated by: KAYA Genetic-Algorithm Scheduler");
            ws.style(1, 0).italic().fontColor("595959").set();

            // ── Row 3: Sorting header ──────────────────────────────────────
            ws.value(3, 0, "HOW THIS SHEET IS SORTED:");
            ws.style(3, 0).bold().set();
            ws.value(4, 0, "  Courses are ordered alphabetically by Course Symbol, then Course Number, then Section Number.");

            // ── Row 6: Column headers (Removed Majors) ─────────────────────
            int headerRow = 6;
            // Columns: Course | Section | Instructor | Room | Days | Start Time | End Time | Teaching Method
            String[] cols = {"Course", "Section", "Instructor", "Room", "Days", "Start Time", "End Time", "Teaching Method"};
            for (int c = 0; c < cols.length; c++) {
                ws.value(headerRow, c, cols[c]);
                ws.style(headerRow, c)
                        .bold()
                        .fontColor(Color.WHITE)
                        .fillColor("2E4057")
                        .set();
            }

            // ── Rows 7+: Data ─────────────────────────────────────────────
            int seq = 0;
            for (Lecture lec : scheduled) {
                int row = headerRow + 1 + seq;
                seq++;

                // Col 0: Course = "SYMBOL NUMBER"
                String courseName = (lec.getCourse().getCourseSymbol() != null ? lec.getCourse().getCourseSymbol() : "")
                        + " " + (lec.getCourse().getCourseNumber() != null ? lec.getCourse().getCourseNumber() : "");
                ws.value(row, 0, courseName.trim());

                // Col 1: Section
                ws.value(row, 1, lec.getSectionNumber() != null ? lec.getSectionNumber() : 0);

                // Col 2: Instructor
                ws.value(row, 2, (lec.getInstructor() != null && lec.getInstructor().getInstructorName() != null) ? lec.getInstructor().getInstructorName() : "");

                // Col 3: Room (Building + Number, and handle ONLINE courses)
                String teachingMethodStr = lec.getCourse().getTeachingMethod() != null ? lec.getCourse().getTeachingMethod().name() : "";

                if ("ONLINE".equals(teachingMethodStr)) {
                    ws.value(row, 3, "-"); // أو تقدر تخليها "" لو حابب الخلية تكون فاضية تماماً
                } else {
                    String building = (lec.getRoom() != null && lec.getRoom().getBuilding() != null) ? lec.getRoom().getBuilding() : "";
                    String roomNum = (lec.getRoom() != null && lec.getRoom().getRoomNumber() != null) ? lec.getRoom().getRoomNumber() : "";
                    ws.value(row, 3, (building + " " + roomNum).trim());
                }

                // Col 4: Days — Restored canonicalGroup so all days of the pattern appear!
                ws.value(row, 4, dayPatternHelper.formatDaysFull(dayPatternHelper.canonicalGroup(lec.getTimeSlot().getDays())));

                // Col 5: Start Time
                ws.value(row, 5, lec.getTimeSlot().getStartTime().toString());

                // Col 6: End Time
                ws.value(row, 6, lec.getTimeSlot().getEndTime().toString());

                // Col 7: Teaching Method
                String method = lec.getCourse().getTeachingMethod() != null
                        ? lec.getCourse().getTeachingMethod().name() : "";
                ws.value(row, 7, method);

                // Alternate row shading (Updates automatically based on cols length)
                if (seq % 2 == 0) {
                    for (int c = 0; c < cols.length; c++) {
                        ws.style(row, c).fillColor("F2F2F2").set();
                    }
                }
            }

            // ── Column widths (Removed width setting for Col 8) ────────────
            ws.width(0, 14);  // Course
            ws.width(1, 9);   // Section
            ws.width(2, 28);  // Instructor
            ws.width(3, 8);   // Room
            ws.width(4, 36);  // Days
            ws.width(5, 12);  // Start Time
            ws.width(6, 12);  // End Time
            ws.width(7, 18);  // Teaching Method

            // ── Unscheduled sheet ──────────────────────────────────────────
            if (!unscheduled.isEmpty()) {
                Worksheet ws2 = wb.newWorksheet("Unscheduled");
                String[] uh = {"#", "Symbol", "Number", "Section", "Instructor"};
                for (int c = 0; c < uh.length; c++) {
                    ws2.value(0, c, uh[c]);
                    ws2.style(0, c).bold().fillColor("C00000").fontColor(Color.WHITE).set();
                }
                for (int r = 0; r < unscheduled.size(); r++) {
                    Lecture lec = unscheduled.get(r);
                    ws2.value(r + 1, 0, r + 1);
                    ws2.value(r + 1, 1, lec.getCourse().getCourseSymbol() != null ? lec.getCourse().getCourseSymbol() : "");
                    ws2.value(r + 1, 2, lec.getCourse().getCourseNumber() != null ? lec.getCourse().getCourseNumber() : "");
                    ws2.value(r + 1, 3, lec.getSectionNumber() != null ? String.valueOf(lec.getSectionNumber()) : "");
                    ws2.value(r + 1, 4, (lec.getInstructor() != null && lec.getInstructor().getInstructorName() != null) ? lec.getInstructor().getInstructorName() : "");
                }
            }
        }

        return xlsxResponse(out, "KAYA_Timetable_" + tt.getId() + ".xlsx");
    }

    private ResponseEntity<byte[]> xlsxResponse(ByteArrayOutputStream out, String filename) {
        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + filename + "\"")
                .header(HttpHeaders.ACCESS_CONTROL_EXPOSE_HEADERS, HttpHeaders.CONTENT_DISPOSITION)
                .contentType(MediaType.parseMediaType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"))
                .body(out.toByteArray());
    }

    private String courseCode(Course c) {
        if (c == null) return "";
        return (c.getCourseSymbol() != null ? c.getCourseSymbol() : "") +
                (c.getCourseNumber() != null ? c.getCourseNumber() : "");
    }
}