package com.kaya.controller;

import com.kaya.model.Lecture;
import java.time.DayOfWeek;
import com.kaya.model.TimeSlot;
import com.kaya.repository.LectureRepository;
import com.kaya.repository.TimeTableRepository;
import lombok.RequiredArgsConstructor;
import org.dhatim.fastexcel.Workbook;
import org.dhatim.fastexcel.Worksheet;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.EnumSet;
import java.util.List;
import java.util.Set;

@RestController
@RequestMapping("/export")
@RequiredArgsConstructor
public class ExportController {

    private final LectureRepository lectureRepository;
    private final TimeTableRepository timeTableRepository;

    private static final DateTimeFormatter TIME_FMT = DateTimeFormatter.ofPattern("HH:mm");

    @GetMapping("/schedule")
    public ResponseEntity<byte[]> exportSchedule() throws Exception {
        List<Lecture> lectures = lectureRepository.findAll().stream()
                .filter(l -> l.getTimeSlot() != null)
                .toList();
        return buildResponse(lectures, "KAYA_Schedule");
    }

    @GetMapping("/schedule/{timetableId}")
    public ResponseEntity<byte[]> exportTimetable(@PathVariable Long timetableId) throws Exception {
        var tt = timeTableRepository.findById(timetableId)
                .orElseThrow(() -> new RuntimeException("Timetable not found"));
        return buildResponse(tt.getLectures(), "KAYA_Timetable_" + timetableId);
    }

    // Group 1: Sunday / Tuesday / Thursday  (STT pattern)
    private static final Set<DayOfWeek> STT = EnumSet.of(DayOfWeek.SUNDAY, DayOfWeek.TUESDAY, DayOfWeek.THURSDAY);
    // Group 2: Monday / Wednesday / Saturday  (MWS pattern — must contain Saturday)
    private static final Set<DayOfWeek> MWS = EnumSet.of(DayOfWeek.MONDAY, DayOfWeek.WEDNESDAY, DayOfWeek.SATURDAY);
    // Group 3: Monday / Wednesday only  (MW — no Saturday)
    private static final Set<DayOfWeek> MW  = EnumSet.of(DayOfWeek.MONDAY, DayOfWeek.WEDNESDAY);

    /** Returns the sort-group rank for a lecture's day pattern (lower = earlier in sheet). */
    private int dayPatternGroup(java.util.Collection<DayOfWeek> days) {
        if (days == null || days.isEmpty()) return 4;
        Set<DayOfWeek> set = EnumSet.copyOf(days);
        if (STT.containsAll(set))                          return 1; // ⊆ {Sun,Tue,Thu}
        if (MWS.containsAll(set) && set.contains(DayOfWeek.SATURDAY)) return 2; // ⊆ {Mon,Wed,Sat} AND has Sat
        if (MW.containsAll(set))                           return 3; // ⊆ {Mon,Wed}
        return 4;                                                     // everything else
    }

    private ResponseEntity<byte[]> buildResponse(List<Lecture> lectures, String filename) throws Exception {
        List<Lecture> sorted = lectures.stream()
                .filter(l -> l.getTimeSlot() != null)
                .sorted(Comparator
                        // Primary: day-pattern group (STT=1, MWS=2, MW=3, other=4)
                        .<Lecture, Integer>comparing(l -> dayPatternGroup(l.getTimeSlot().getDays()))
                        // Secondary: start time (earliest first)
                        .thenComparing(l -> l.getTimeSlot().getStartTime())
                        // Tertiary: course code alphabetically
                        .thenComparing(l -> l.getCourse() != null
                                ? l.getCourse().getCourseSymbol() + l.getCourse().getCourseNumber() : ""))
                .toList();

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try (Workbook wb = new Workbook(out, "KAYA Scheduler", "1.0")) {
            Worksheet ws = wb.newWorksheet("Schedule");

            // ── Legend / note block ──────────────────────────────────────────
            ws.value(0, 0, "KAYA – University Course Timetable System (Yarmouk University)");
            ws.style(0, 0).bold().fontSize(13).set();

            ws.value(1, 0, "Generated by: KAYA Genetic-Algorithm Scheduler");
            ws.style(1, 0).italic().set();

            // Blank separator
            // row 2 intentionally empty

            ws.value(3, 0, "HOW THIS SHEET IS SORTED:");
            ws.style(3, 0).bold().set();

            ws.value(4, 0, "  Group 1 — Sunday / Tuesday / Thursday (STT pattern)  →  courses that meet on Sun, Tue, Thu");
            ws.value(5, 0, "  Group 2 — Monday / Wednesday / Saturday (MWS pattern)  →  courses that meet on Mon, Wed, Sat");
            ws.value(6, 0, "  Group 3 — Monday / Wednesday (MW pattern)  →  courses that meet on Mon, Wed only");
            ws.value(7, 0, "  Group 4 — All other day combinations (listed last)");
            ws.value(8, 0, "  Within each group, courses are ordered by Start Time (earliest first), then alphabetically by Course code.");

            for (int r = 4; r <= 8; r++) ws.style(r, 0).italic().set();

            // Blank separator
            // row 9 intentionally empty

            // ── Column headers ───────────────────────────────────────────────
            String[] headers = {"Course", "Section", "Instructor / Teacher", "Room",
                    "Days", "Start Time", "End Time", "Teaching Method", "Majors"};
            for (int col = 0; col < headers.length; col++) {
                ws.value(10, col, headers[col]);
                ws.style(10, col).bold().set();
            }

            int row = 11;
            for (Lecture l : sorted) {
                ws.value(row, 0, l.getCourse() != null
                        ? l.getCourse().getCourseSymbol() + " " + l.getCourse().getCourseNumber() : "");
                ws.value(row, 1, l.getSectionNumber() != null ? l.getSectionNumber().toString() : "1");
                String teacher = l.getTeacher() != null ? l.getTeacher().getName()
                        : (l.getInstructor() != null ? l.getInstructor() : "");
                ws.value(row, 2, teacher);
                ws.value(row, 3, l.getRoom() != null
                        ? l.getRoom().getBuilding() + " " + l.getRoom().getRoomNumber() : "");

                TimeSlot ts = l.getTimeSlot();
                if (ts != null) {
                    ws.value(row, 4, ts.getDays().toString().replaceAll("[\\[\\]]", ""));
                    ws.value(row, 5, ts.getStartTime().format(TIME_FMT));
                    ws.value(row, 6, ts.getEndTime().format(TIME_FMT));
                    ws.value(row, 7, ts.getTeachingMethod() != null ? ts.getTeachingMethod().name() : "");
                }
                ws.value(row, 8, l.getCourse() != null
                        ? String.join(", ", l.getCourse().getMajors()) : "");
                row++;
            }
        }

        byte[] bytes = out.toByteArray();
        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + filename + ".xlsx\"")
                .contentType(MediaType.parseMediaType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"))
                .contentLength(bytes.length)
                .body(bytes);
    }
}
