/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimeSlotsRouteImport } from './routes/time-slots'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as InstructorsRouteImport } from './routes/instructors'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const TimeSlotsRoute = TimeSlotsRouteImport.update({
  id: '/time-slots',
  path: '/time-slots',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsRoute = InstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/instructors': typeof InstructorsRoute
  '/rooms': typeof RoomsRoute
  '/time-slots': typeof TimeSlotsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/instructors': typeof InstructorsRoute
  '/rooms': typeof RoomsRoute
  '/time-slots': typeof TimeSlotsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/instructors': typeof InstructorsRoute
  '/rooms': typeof RoomsRoute
  '/time-slots': typeof TimeSlotsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/instructors' | '/rooms' | '/time-slots'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/instructors' | '/rooms' | '/time-slots'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/instructors'
    | '/rooms'
    | '/time-slots'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  InstructorsRoute: typeof InstructorsRoute
  RoomsRoute: typeof RoomsRoute
  TimeSlotsRoute: typeof TimeSlotsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/time-slots': {
      id: '/time-slots'
      path: '/time-slots'
      fullPath: '/time-slots'
      preLoaderRoute: typeof TimeSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors': {
      id: '/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof InstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  InstructorsRoute: InstructorsRoute,
  RoomsRoute: RoomsRoute,
  TimeSlotsRoute: TimeSlotsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
