/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimeSlotsRouteImport } from './routes/time-slots'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as LecturesRouteImport } from './routes/lectures'
import { Route as InstructorsRouteImport } from './routes/instructors'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ConflictsRouteImport } from './routes/conflicts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScheduleIdRouteImport } from './routes/schedule.$id'

const TimeSlotsRoute = TimeSlotsRouteImport.update({
  id: '/time-slots',
  path: '/time-slots',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturesRoute = LecturesRouteImport.update({
  id: '/lectures',
  path: '/lectures',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsRoute = InstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictsRoute = ConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIdRoute = ScheduleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ScheduleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conflicts': typeof ConflictsRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/instructors': typeof InstructorsRoute
  '/lectures': typeof LecturesRoute
  '/rooms': typeof RoomsRoute
  '/schedule': typeof ScheduleRouteWithChildren
  '/time-slots': typeof TimeSlotsRoute
  '/schedule/$id': typeof ScheduleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conflicts': typeof ConflictsRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/instructors': typeof InstructorsRoute
  '/lectures': typeof LecturesRoute
  '/rooms': typeof RoomsRoute
  '/schedule': typeof ScheduleRouteWithChildren
  '/time-slots': typeof TimeSlotsRoute
  '/schedule/$id': typeof ScheduleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conflicts': typeof ConflictsRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/instructors': typeof InstructorsRoute
  '/lectures': typeof LecturesRoute
  '/rooms': typeof RoomsRoute
  '/schedule': typeof ScheduleRouteWithChildren
  '/time-slots': typeof TimeSlotsRoute
  '/schedule/$id': typeof ScheduleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conflicts'
    | '/courses'
    | '/dashboard'
    | '/instructors'
    | '/lectures'
    | '/rooms'
    | '/schedule'
    | '/time-slots'
    | '/schedule/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conflicts'
    | '/courses'
    | '/dashboard'
    | '/instructors'
    | '/lectures'
    | '/rooms'
    | '/schedule'
    | '/time-slots'
    | '/schedule/$id'
  id:
    | '__root__'
    | '/'
    | '/conflicts'
    | '/courses'
    | '/dashboard'
    | '/instructors'
    | '/lectures'
    | '/rooms'
    | '/schedule'
    | '/time-slots'
    | '/schedule/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConflictsRoute: typeof ConflictsRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  InstructorsRoute: typeof InstructorsRoute
  LecturesRoute: typeof LecturesRoute
  RoomsRoute: typeof RoomsRoute
  ScheduleRoute: typeof ScheduleRouteWithChildren
  TimeSlotsRoute: typeof TimeSlotsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/time-slots': {
      id: '/time-slots'
      path: '/time-slots'
      fullPath: '/time-slots'
      preLoaderRoute: typeof TimeSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lectures': {
      id: '/lectures'
      path: '/lectures'
      fullPath: '/lectures'
      preLoaderRoute: typeof LecturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors': {
      id: '/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof InstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflicts': {
      id: '/conflicts'
      path: '/conflicts'
      fullPath: '/conflicts'
      preLoaderRoute: typeof ConflictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/$id': {
      id: '/schedule/$id'
      path: '/$id'
      fullPath: '/schedule/$id'
      preLoaderRoute: typeof ScheduleIdRouteImport
      parentRoute: typeof ScheduleRoute
    }
  }
}

interface ScheduleRouteChildren {
  ScheduleIdRoute: typeof ScheduleIdRoute
}

const ScheduleRouteChildren: ScheduleRouteChildren = {
  ScheduleIdRoute: ScheduleIdRoute,
}

const ScheduleRouteWithChildren = ScheduleRoute._addFileChildren(
  ScheduleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConflictsRoute: ConflictsRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  InstructorsRoute: InstructorsRoute,
  LecturesRoute: LecturesRoute,
  RoomsRoute: RoomsRoute,
  ScheduleRoute: ScheduleRouteWithChildren,
  TimeSlotsRoute: TimeSlotsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
